### ISSUE TITLE
Font Awsome Now at Version 6

### ISSUE THREAD

**Issue by nyambol** [kcyarn/pretty-speedbar#1]
Hello,

FA has released v6. Don't know if this is directly affecting your code. I had to set `pretty-speedbar-font` explicitly to get `pretty` to work. Looks great! 

Thanks.
mp

**Comment by kcyarn** [comment]
Thanks for the heads-up! I'll take a look at v6 and see if anything needs an update other than the font name.

________________________________
From: Michael Powe ***@***.***>
Sent: Sunday, February 20, 2022 1:28 PM
To: kcyarn/pretty-speedbar
Cc: Subscribed
Subject: [kcyarn/pretty-speedbar] Font Awsome Now at Version 6 (Issue #1)

Hello,
FA has released v6. Don't know if this is directly affecting your code. I had to set pretty-speedbar-font explicitly to get pretty to work. Looks great!
Thanks.
mp
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kcyarn** [comment]
56dc9f114fcc55843e182cde1fc9d7a14c261c6a

Updated to Font Awesome 6. Thanks again!

**Comment by nyambol** [comment]
Glad to be useful, instead of just another complainer. ;-)
